# netlify.toml
[[headers]]
  # Aplica estos encabezados a todos los archivos CSS
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  # Aplica estos encabezados a todos los archivos de imágenes
  for = "*.png"
  [headers.values]
    Content-Type = "image/png"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Content-Type = "image/jpeg"

[[headers]]
  for = "*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"

[build]
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "18"
